### ISSUE TITLE
unknown this.editor referencing.

### ISSUE THREAD

**Issue by binarytracer** [MaaxGr/ang-jsoneditor#10]
![image](https://user-images.githubusercontent.com/8814442/178213428-4867a122-58c9-41b7-b0b7-98c70f44a369.png)
it seems `this.editor` is undefined and being reference here again with 
![image](https://user-images.githubusercontent.com/8814442/178215868-99e1bd60-4651-4ea0-b425-85977316e751.png)

Is there i away to fix this one?
Is not causing any functionality issues so far, but i just want to make the console cleaner.

**Comment by MaaxGr** [comment]
Should be fixed with 13.0.5. Can you confirm?
(You are using Angular 13?)

**Comment by binarytracer** [comment]
yes! its fixed man, thanks @MaaxGr .
