### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by yogesh1140** [MaaxGr/ang-jsoneditor#11]
Any timeline available for angular 14 upgrade?

**Comment by MaaxGr** [comment]
No. But feel free to submit a Pull Request. :)

**Comment by MartinKei** [comment]
@MaaxGr

@hcsatoshiwatanabe did create a pull request - any chance that you merge than soon?

**Comment by YemreGurses** [comment]
can we merge the corresponding pr and update npm packages for angular 14?

**Comment by MaaxGr** [comment]
I will try to look into it today evening.

**Comment by MaaxGr** [comment]
Hey together. V14 is now released. Thanks for your merge request :)
https://www.npmjs.com/package/@maaxgr/ang-jsoneditor/v/14.0.0
